"""
Interactive Map Visualization module for PathFinder (Stage 2).

Uses Folium to render interactive HTML maps with:
- Start and destination markers (custom icons and tooltips)
- High-visibility polyline tracing exact road geometries
- Floating trip metrics HUD (distance, time, nodes explored)
- Fit-to-bounds auto-framing
"""

from __future__ import annotations
import os
from typing import List, Optional, Tuple

from graph import Graph
from dijkstra import PathResult


def generate_interactive_map(
    graph: Graph,
    result: PathResult,
    start_coord: Tuple[float, float],
    dest_coord: Tuple[float, float],
    start_label: str = "Origin",
    dest_label: str = "Destination",
    output_path: str = "route_map.html",
) -> str:
    """
    Generate an interactive Folium HTML map visualizing the calculated route.

    Args:
        graph: The Graph containing road nodes and edge geometries.
        result: The PathResult generated by Dijkstra's algorithm.
        start_coord: (lat, lon) of origin.
        dest_coord: (lat, lon) of destination.
        start_label: Name of the origin location.
        dest_label: Name of the destination location.
        output_path: Path where HTML file should be saved.

    Returns:
        Absolute path to the created HTML file.
    """
    try:
        import folium
    except ImportError as e:
        raise ImportError(
            "Folium is required for interactive map visualization. "
            "Install it via: pip install folium"
        ) from e

    # Calculate center of coordinates
    mid_lat = (start_coord[0] + dest_coord[0]) / 2.0
    mid_lon = (start_coord[1] + dest_coord[1]) / 2.0

    # Initialize Folium Map
    m = folium.Map(
        location=[mid_lat, mid_lon],
        zoom_start=15,
        tiles="OpenStreetMap",
        control_scale=True,
    )

    all_points: List[List[float]] = []

    # Reconstruct polyline points from edge geometries or node coordinates
    if result.found and len(result.path) >= 2:
        for u, v in zip(result.path[:-1], result.path[1:]):
            edge = graph.get_edge(u, v)
            if edge and edge.geometry:
                for pt in edge.geometry:
                    all_points.append([pt[0], pt[1]])
            else:
                u_coord = graph.get_node_coords(u)
                v_coord = graph.get_node_coords(v)
                if u_coord:
                    all_points.append([u_coord[0], u_coord[1]])
                if v_coord:
                    all_points.append([v_coord[0], v_coord[1]])

    # Format distance nicely
    if result.total_distance >= 1000:
        dist_display = f"{result.total_distance / 1000:.2f} km"
    else:
        dist_display = f"{result.total_distance:.0f} meters"

    time_display = f"{result.execution_time_sec * 1000:.2f} ms"

    # Add Route PolyLine if points exist
    if all_points:
        folium.PolyLine(
            locations=all_points,
            color="#2563EB",  # Vibrant royal blue
            weight=6,
            opacity=0.85,
            popup=f"Route: {start_label} ➔ {dest_label}<br>Distance: {dist_display}",
            tooltip=f"Shortest Route ({dist_display})",
        ).add_to(m)

        # Connect user GPS coordinate to the first road node if slightly off-road
        first_node_coord = graph.get_node_coords(result.path[0])
        if first_node_coord and (first_node_coord[0] != start_coord[0] or first_node_coord[1] != start_coord[1]):
            folium.PolyLine(
                locations=[[start_coord[0], start_coord[1]], [first_node_coord[0], first_node_coord[1]]],
                color="#10B981",
                weight=3,
                dash_array="6",
                tooltip="Access to road network",
            ).add_to(m)

        # Connect last road node to user destination coordinate
        last_node_coord = graph.get_node_coords(result.path[-1])
        if last_node_coord and (last_node_coord[0] != dest_coord[0] or last_node_coord[1] != dest_coord[1]):
            folium.PolyLine(
                locations=[[last_node_coord[0], last_node_coord[1]], [dest_coord[0], dest_coord[1]]],
                color="#EF4444",
                weight=3,
                dash_array="6",
                tooltip="Final arrival step",
            ).add_to(m)

    # Origin Marker (Green)
    start_html = f"""
    <div style="font-family: Arial, sans-serif; min-width: 140px;">
        <h4 style="margin: 0 0 5px 0; color: #059669;">🚩 Start</h4>
        <b>{start_label}</b><br>
        <span style="font-size: 11px; color: #666;">Lat: {start_coord[0]:.5f}, Lon: {start_coord[1]:.5f}</span>
    </div>
    """
    folium.Marker(
        location=[start_coord[0], start_coord[1]],
        popup=folium.Popup(start_html, max_width=250),
        tooltip=f"Start: {start_label}",
        icon=folium.Icon(color="green", icon="play", prefix="fa"),
    ).add_to(m)

    # Destination Marker (Red)
    dest_html = f"""
    <div style="font-family: Arial, sans-serif; min-width: 140px;">
        <h4 style="margin: 0 0 5px 0; color: #DC2626;">🏁 Destination</h4>
        <b>{dest_label}</b><br>
        <span style="font-size: 11px; color: #666;">Lat: {dest_coord[0]:.5f}, Lon: {dest_coord[1]:.5f}</span>
    </div>
    """
    folium.Marker(
        location=[dest_coord[0], dest_coord[1]],
        popup=folium.Popup(dest_html, max_width=250),
        tooltip=f"Destination: {dest_label}",
        icon=folium.Icon(color="red", icon="flag", prefix="fa"),
    ).add_to(m)

    # Floating HUD Card / Dashboard
    info_card_html = f"""
    <div style="
        position: fixed;
        top: 15px;
        right: 15px;
        z-index: 1000;
        background-color: white;
        padding: 14px 18px;
        border-radius: 8px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.25);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        font-size: 13px;
        max-width: 320px;
        border-left: 5px solid #2563EB;
    ">
        <div style="font-size: 15px; font-weight: bold; color: #1E293B; margin-bottom: 6px;">
            🧭 PathFinder Route Navigator
        </div>
        <div style="color: #475569; margin-bottom: 8px;">
            <b>From:</b> {start_label}<br>
            <b>To:</b> {dest_label}
        </div>
        <hr style="border: 0; border-top: 1px solid #E2E8F0; margin: 8px 0;">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 6px; font-size: 12px;">
            <div>📏 <b>Distance:</b> {dist_display}</div>
            <div>⚡ <b>Time:</b> {time_display}</div>
            <div>🛣️ <b>Segments:</b> {len(result.legs)}</div>
            <div>🔍 <b>Nodes:</b> {result.visited_nodes_count}</div>
        </div>
        <div style="margin-top: 8px; font-size: 11px; color: #64748B; font-style: italic;">
            Calculated via Dijkstra's Algorithm (from scratch)
        </div>
    </div>
    """
    m.get_root().html.add_child(folium.Element(info_card_html))

    # Auto fit bounds
    bounds_points = [[start_coord[0], start_coord[1]], [dest_coord[0], dest_coord[1]]]
    if all_points:
        bounds_points.extend(all_points)
    m.fit_bounds(bounds_points, padding=[30, 30])

    abs_output = os.path.abspath(output_path)
    os.makedirs(os.path.dirname(abs_output), exist_ok=True)
    m.save(abs_output)

    return abs_output
